### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by mihi-r** [mihi-r/ceas-tribunal-tv-submission#3]
Two database tables will need to be created. One table will be storing general admin information and the second table will include the details of each tv submission.

tv_submission_info:
- id (auto-incrementing int primary key)
- admin_name (varchar 256)
- admin_email (varchar 256)

tv_submissions:
- id (auto-incrementing int primary key)
- name (varchar 256)
- org_name (varchar 256)
- email (varchar 256)
- description (text)

**Comment by mihi-r** [comment]
@huber2jb Do you know how you can do this in MAMP? As a reminder, you can create the tables there and then export it. When exporting it, you can just export the structure to a SQL file. Afterward, create a folder called schema and add all of the SQL files there. You can refer to the [Resume Review Day](https://github.com/mihi-r/resume-review-day) repo as an example.

**Comment by huber2jb** [comment]
@mihi-r Might have to tell me everything I need to install again because I got my new laptop and haven't installed like anything on this

**Comment by mihi-r** [comment]
@huber2jb Alright, see if the [README](https://github.com/mihi-r/ceas-tribunal-tv-submission/blob/master/README.md) can help then. It should have all of the required programs. 🙂
